import openai
import os


class Chatbot:
    """
    Connects to the Chatbot OpenAI API
    """
    def __init__(self):
        openai.api_key = os.getenv('OPENAI_API_KEY')

    def get_response(self, user_input):
        """
        Retrieves a response from the chatbot based on a user input
        :param user_input: The text entered by the user to which the chatbot is
        responding
        :return: The response generated by the chatbot
        """
        api_response = openai.Completion.create(
            engine="text-davinci-003",
            prompt=user_input,
            max_tokens=3000,
            temperature=0.5
        ).choices[0].text

        return api_response


if __name__ == "__main__":
    chatbot = Chatbot()
    query = "Write a joke about birds"
    response = chatbot.get_response(query)
    print(response)
